[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
postcard = { version = "1.1.1", features = ["use-crc"] }
serde = { version = "1.0.219", features = ["derive"] }
harmony_core = { path = "../harmony_core" }
